### ISSUE TITLE
Copy information into closure button

### ISSUE THREAD

**Issue by Glodenox** [Glodenox/wme-road-events#10]
We could enhance the closure form by adding a link or button to copy any currently opened GIPOD information into the closure. Information that could be copied over: startDateTime, endDateTime and description (perhaps, as it might be too long).

Because I have no access to this form, I'll have to dig into the code to figure out how that works.

**Comment by sirKitKat** [comment]
~~Could it be it is not working yet?~~ nevermind, found it :)
