### ISSUE TITLE
Change Timestamp notations

### ISSUE THREAD

**Issue by sirKitKat** [Glodenox/wme-road-events#12]
Change the date/time notations from the iso form:
2015-09-28T07:00
to some thing more readable:
2015-09-28   07:00
(The T is replaced with 3 spaces)

**Comment by Glodenox** [comment]
I've made some changes (not yet published) which turn periods into this format:
2015-05-19 08:00 - 2015-11-19 17:00

I originally kept in the "T" as the time of the second timestamp kept on moving to a new line and adding a non-breaking space in-between would've required me to rewrite quite a bit of the code. But I've just tested this and it works fine now.
