### ISSUE TITLE
Timezone not consistent

### ISSUE THREAD

**Issue by Hipska** [Glodenox/wme-road-events#18]
The additional information in search result list has (for GIPOD) different time then in detail view in the field Period.

**Comment by Glodenox** [comment]
Could you give me an example? I'm not seeing any differences in the cases I've checked. Also, I presume you're really talking about the userscript and not the community dashboard, right?

**Comment by Hipska** [comment]
You can pick any item, it happens on all of them:
![Search result list](https://www.dropbox.com/s/k49y30myg10qgt8/Screenshot%202017-01-18%2014.56.42.png?dl=1) versus ![Detail view](https://www.dropbox.com/s/pjau3h5byrih4g1/Screenshot%202017-01-18%2014.59.05.png?dl=1)
WME OpenMaps GIPOD layer shows 6:00 to 19:00 as time period.

**Comment by Glodenox** [comment]
Ah indeed. Chrome-only bug apparently. It would seem the browser tries to 'help' by factoring in the time zone.

**Comment by Hipska** [comment]
I think this is already fixed?

**Comment by Glodenox** [comment]
I'm afraid I haven't released the bugfix for this yet, no. I've been adjusting the script so it can get its information from external sources directly instead of through a proxy, but that changes the execution context of the userscript, requiring many changes in the DOM-related operations.

**Comment by Glodenox** [comment]
I've put running the userscript in a separate context on another branch now, so I could fix this issue. To fix the `[object Object]` indications and remove the proxy, I'll need to get that separate context working.
