### ISSUE TITLE
JSON parse error for GIPOD sources

### ISSUE THREAD

**Issue by Hipska** [Glodenox/wme-road-events#21]
The GIPOD sources give JSON parse errors on the following lines:
https://github.com/Glodenox/wme-road-events/blob/15431530009b678e68ff8b263fe976bb0d86fbb5/WME_Road_Events_Data.user.js#L639
https://github.com/Glodenox/wme-road-events/blob/15431530009b678e68ff8b263fe976bb0d86fbb5/WME_Road_Events_Data.user.js#L511
The message Chrome gives is:
> Uncaught SyntaxError: Unexpected token u in JSON at position 0

**Comment by Glodenox** [comment]
Fixed with commit 3f2daeec527dddb85bdf7b3fdac4ab6bd8f41b6b.
It turned out that the proxy I wrote was still relying on the old API location. The proxy has now been removed as the source is now available over HTTPS.
