### ISSUE TITLE
Geopunt button

### ISSUE THREAD

**Issue by WimVandierendonck** [Glodenox/wme-road-events#3]
Nice to Have.
Zou handig zijn om in de GIPOD tab een knop 'open huidge locatie in Geopunt' te hebben.
Geopunt coördinaten links zien er als volgt uit: http://www.geopunt.be/kaart?app=Geopunt-kaart_app&coordinaten=50.97186%203.18815

**Comment by Glodenox** [comment]
Zou niet al te moeilijk mogen zijn. Ik heb net even gekeken of het ook mogelijk was om naar de "hinder in beeld"-kaart te linken, maar dat is blijkbaar wat moeilijker omdat ze daar met een of ander id werken in de URL.

**Comment by WimVandierendonck** [comment]
Mij was het vooral om de snelle link naar geopunt te doen ;-).
Maar mss is er daar al een bestaande oplossing voor. Moet ik nog even zoeken. Dus nog niet meteen doen.

**Comment by Glodenox** [comment]
Een link naar Geopunt zou ik dan liever in een apart userscript toevoegen. Maar ik ga sowieso eerst proberen om de GRB Basiskaart van Geopunt in WME toe te voegen. Dan zou zo'n link sowieso niet meer nodig zijn, lijkt me.
