### ISSUE TITLE
Prefix variabelen

### ISSUE THREAD

**Issue by WimVandierendonck** [Glodenox/wme-road-events#5]
https://wiki.waze.com/wiki/Community_Plugins,_Extensions_and_Tools/WME_JavaScript_development#Prefix_for_variables_and_functions

**Comment by Glodenox** [comment]
Dat deed ik al in mijn scripts voordat ik dat op de wiki tegen kwam. In de scripts die ik geschreven heb worden er geen publieke variabelen aangemaakt of publieke functies toegevoegd. Het hele script zit verwerkt in een naamloze functie die meteen wordt uitgevoerd, waardoor er geen enkel risico bestaat op name collisions.

**Comment by WimVandierendonck** [comment]
Ah, had er geen idee van dat dat de reden daarvan was. Oeps.
